from typing import Any

from app.ai.embedding_client import generate_embedding
from app.core.config import settings
from app.repositories.document_chunk_repository import (
    get_all_active_chunks,
    update_chunk_embedding,
)


def chunk_has_valid_embedding(
    chunk: dict[str, Any],
) -> bool:
    """
    Check whether a chunk already contains a usable embedding
    generated by the configured model.
    """
    embedding = chunk.get("embedding")
    embedding_model = chunk.get("embedding_model")
    embedding_dimensions = chunk.get(
        "embedding_dimensions"
    )

    if not isinstance(embedding, list):
        return False

    if not embedding:
        return False

    if embedding_model != settings.embedding_model:
        return False

    if embedding_dimensions != len(embedding):
        return False

    return True


async def backfill_missing_chunk_embeddings() -> dict[
    str,
    Any,
]:
    """
    Generate embeddings for active chunks that do not already
    contain a valid embedding.

    Individual failures are reported without stopping the full
    backfill operation.
    """
    chunks = await get_all_active_chunks()

    result: dict[str, Any] = {
        "total_chunks": len(chunks),
        "processed_chunks": 0,
        "skipped_chunks": 0,
        "failed_chunks": 0,
        "failures": [],
    }

    for chunk in chunks:
        if chunk_has_valid_embedding(chunk):
            result["skipped_chunks"] += 1
            continue

        try:
            embedding = await generate_embedding(
                chunk["content"]
            )

            updated = await update_chunk_embedding(
                chunk_id=chunk["id"],
                embedding=embedding,
                embedding_model=settings.embedding_model,
            )

            if not updated:
                raise RuntimeError(
                    "Chunk embedding update failed."
                )

            result["processed_chunks"] += 1

        except Exception as exc:
            result["failed_chunks"] += 1

            result["failures"].append(
                {
                    "chunk_id": chunk["id"],
                    "document_id": chunk["document_id"],
                    "document_title": (
                        chunk["document_title"]
                    ),
                    "chunk_index": chunk["chunk_index"],
                    "error": str(exc),
                }
            )

    return result